### ISSUE TITLE
Ability to send push notifications when new keys are detected

### ISSUE THREAD

**Issue by HendX** [CrunchyBagel/TracePrivately#13]
This may not scale if you have to ping every single client with a push notification, but it may be useful way to wake up people's phones for exposure checking.

**Comment by tatey** [comment]
Do you see the notification containing a list of the infected keys, or should the client use the notification to wake up and get new keys from the `/api/infected` endpoint?

The problem with the former is I think there's a limit to the payload size on push notifications?

The problem with latter is that the server is basically asking to DoS itself. If the server sends out 1m notifications then 1m clients would make a request to the server. The server would either need to stagger the notifications, or the client would need to stagger the request.

**Comment by HendX** [comment]
I was thinking just to wake up the client to retrieve the new keys. But you're right, this is likely a bad idea.

One of the features I implemented yesterday was background checking for new infections. The only problem is that if an app is force quit then it won't wake up for background checking.

However a silent push notification will launch the app in the background. So maybe a push notification, but the app can only check a minimum of every, say, 30 minutes. So even if it received a silent push this would just wake it up in the case where it's otherwise been terminated.

More thought needed on this.

**Comment by HendX** [comment]
I'm closing this now as it has been implemented using local notifications and periodic exposure checking in the background, which I believe to be the appropriate way to achieve this.
